// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatrack.proto

package com.example.ss.protos;

public final class DataTrackingOuterClass {
  private DataTrackingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_DataTracking_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_DataTracking_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017datatrack.proto\022\010tutorial\"l\n\014DataTrack" +
      "ing\022\017\n\007version\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\021\n\tti" +
      "mestamp\030\003 \002(\006\022\020\n\010phone_id\030\004 \001(\t\022\013\n\003lon\030\005" +
      " \001(\006\022\013\n\003lat\030\006 \001(\006B2\n\026com.example.ss.prot" +
      "os1B\026DataTrackingOuterClassP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_DataTracking_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_DataTracking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_DataTracking_descriptor,
        new java.lang.String[] { "Version", "Name", "Timestamp", "PhoneId", "Lon", "Lat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
